# Get state of an entity.
# Support for this interface is indicated through the ENTITY_STATE_GETTING value in GetSimulationFeatures.

string entity                         # Entity identified by its unique name as returned by GetEntities / SpawnEntity.

---

Result result
EntityState state                     # Entity ground truth state. Valid when result.result = OK.
