# Gets the simulation state (paused, playing, stopped)
# Support for this interface is indicated through the SIMULATION_STATE_GETTING value in GetSimulationFeatures.

---

SimulationState state                      # Current state of the simulation.

Result result
